CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,1,2,3)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 16
PRINT_FREQ: 100

DATASET:
  DATASET: mapillary
  ROOT: "/root/autodl-tmp/DSNet/data/"
  TEST_SET: 'list/mapillary/val.lst'
  TRAIN_SET: 'list/mapillary/train.lst'
  NUM_CLASSES: 66
MODEL:
  NAME: "dsnet_head128"
  NUM_OUTPUTS: 3
  PRETRAINED: ""
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 1536
  - 768
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 160
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 1536
  - 768
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  MULTI_SCALE: false 
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
